force_cast: error

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 80
    error: 90
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  excluded: # excluded via string array
    - id
    - BASE_URL
    - API_KEY


excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - WatchBloggeriOSTest